---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= BlueXP 랜섬웨어 방어에 관한 FAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 액세스

* BlueXP 랜섬웨어 방어 URL은 무엇입니까? *
URL의 경우 브라우저에 다음을 입력합니다. https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] 를 눌러 BlueXP 콘솔에 액세스합니다.

* BlueXP 랜섬웨어 보호를 사용하려면 라이센스가 필요하십니까? *
NetApp 라이센스 파일(NLF)은 필요하지 않습니다. BlueXP 랜섬웨어 방어 사전 공개 자체에는 특별한 라이센스가 필요하지 않습니다.  모든 Preview 라이선스는 평가판 라이선스입니다.

이 서비스의 미리 보기 버전에는 BlueXP 백업 및 복구 서비스 라이센스가 필요합니다.


TIP: Preview 버전의 경우 NetApp는 평가판 및 필요한 모든 라이센스를 설정할 수 있도록 도와줍니다.

* BlueXP 랜섬웨어 보호를 어떻게 활성화하시겠습니까? *
BlueXP 랜섬웨어 방어에 도움이 필요하지 않습니다. 랜섬웨어 방지 옵션은 BlueXP 왼쪽 탐색 창에서 자동으로 활성화됩니다.

Preview 버전의 경우 이 서비스를 체험하려면 등록하거나 NetApp 영업 담당자에게 연락해야 합니다. BlueXP Connector를 사용하면 서비스에 적합한 기능이 여기에 포함됩니다.

** BlueXP 랜섬웨어 보호는 표준, 제한 및 프라이빗 모드로 사용할 수 있습니까?**
현재 BlueXP 랜섬웨어 보호는 표준 모드에서만 제공됩니다. 많은 관심 부탁드립니다.

모든 BlueXP 서비스 전체에서 이러한 모드에 대한 설명은 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드"^].

** 액세스 권한은 어떻게 처리됩니까?**
계정 관리자만 서비스를 시작하고 워크로드를 검색할 수 있습니다(리소스 사용을 커밋하는 작업이 포함되므로). 이후 상호 작용은 모든 역할에 의해 수행될 수 있습니다.

** 어떤 장치 해상도가 가장 좋습니까?**
BlueXP 랜섬웨어 방어에 권장되는 장치 해상도는 1920x1080 이상입니다.

** 어떤 브라우저를 사용해야 합니까?**
모든 최신 브라우저가 작동합니다.



== 다른 서비스와의 상호 작용

* BlueXP 랜섬웨어 방어는 NetApp ONTAP의 보호 설정을 인식합니까? *
예, BlueXP 랜섬웨어 보호는 ONTAP에서 설정된 스냅샷 일정을 검색합니다.

* BlueXP 랜섬웨어 보호를 사용하여 정책을 설정한 경우 향후 이 서비스에서만 변경해야 합니까? *
아니요, 모든 서비스에서 정책을 변경할 수 있습니다.



== 워크로드

**업무량을 구성하는 요소는 무엇입니까?**
워크로드에는 단일 애플리케이션 인스턴스에서 사용하는 모든 볼륨이 포함됩니다. 예를 들어, ora3.host.com 에 구축된 Oracle DB 인스턴스는 해당 데이터와 로그에 대해 각각 vol1과 vol2를 가질 수 있습니다. 이러한 볼륨은 모두 Oracle DB 인스턴스의 특정 인스턴스에 대한 워크로드를 구성합니다.

* BlueXP 랜섬웨어 방어는 워크로드 데이터의 우선순위를 어떻게 정합니까? *
Preview 버전의 데이터 우선 순위는 생성된 스냅샷 복사본과 예약된 백업에 의해 결정됩니다.

워크로드 우선 순위는 다음과 같은 스냅샷 주파수에 의해 결정됩니다.

* * 중요 *: 시간당 1개 미만의 스냅샷 복사본 생성(매우 공격적인 보호 일정)
* * 중요 *: 매일 1회 미만으로 스냅샷 복사본을 생성합니다
* * 표준 *: 매일 1개 이상의 스냅샷 복사본이 생성됩니다


** 새 볼륨이 추가되었지만 아직 나타나지 않습니다**
환경에 새 볼륨을 추가한 경우 검색을 다시 시작하고 보호 정책을 적용하여 새 볼륨을 보호합니다.

** 대시보드에 내 작업 부하가 모두 표시되지 않습니다. 무엇이 잘못되었을 수 있습니까?**
현재 NFS 볼륨만 지원됩니다. iSCSI 볼륨, CIFS 볼륨 및 기타 지원되지 않는 구성은 필터링되어 대시보드에 표시되지 않습니다.



== 보호 정책

* BlueXP 랜섬웨어 정책은 다른 종류의 워크로드 정책과 공존합니까? *
현재 BlueXP 백업 및 복구(Cloud Backup)는 볼륨당 하나의 백업 정책을 지원합니다. BlueXP 백업 및 복구와 BlueXP 랜섬웨어 방어는 백업 정책을 공유합니다.

Snapshot 복사본은 제한되지 않으며 각 서비스와 별도로 추가할 수 있습니다.
