---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= BlueXP 랜섬웨어 방어에 관한 FAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 구축

* BlueXP 랜섬웨어 보호를 사용하려면 라이센스가 필요하십니까? *

다음과 같은 라이센스 유형을 사용할 수 있습니다.

* 90일 무료 평가판을 신청하십시오.
* 곧 AWS(Amazon Web Services) Marketplace를 통해 PAYGO(용량제) 구독을 구입할 수 있습니다.
* 조만간 BYOL(Bring Your Own NetApp License File)이라는 BYOL(Bring Your Own License File)을 받을 수 있게 됩니다 NetApp 라이센스 일련 번호를 사용하여 BlueXP 디지털 지갑에서 BYOL을 활성화할 수 있습니다.


* BlueXP 랜섬웨어 보호를 어떻게 활성화하시겠습니까? *
BlueXP 랜섬웨어 방어에 도움이 필요하지 않습니다. 랜섬웨어 방지 옵션은 BlueXP 왼쪽 탐색 창에서 자동으로 활성화됩니다.

이 서비스를 이용하려면 등록하거나 NetApp 영업 담당자에게 연락하여 이 서비스를 체험해 보십시오. BlueXP Connector를 사용하면 서비스에 적합한 기능이 여기에 포함됩니다.

BlueXP  랜섬웨어 보호를 시작하려면 초기 랜딩 페이지에서 "워크로드 발견 시작"을 클릭하십시오.

* BlueXP  랜섬웨어 방어는 표준, 제한 및 비공개 모드로 사용할 수 있습니까? * 현재 BlueXP 랜섬웨어 보호는 표준 모드에서만 제공됩니다. 많은 관심 부탁드립니다.

모든 BlueXP 서비스 전체에서 이러한 모드에 대한 설명은 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드"^].



== 액세스

* BlueXP 랜섬웨어 방어 URL은 무엇입니까? *
URL의 경우 브라우저에 다음을 입력합니다. https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] 를 눌러 BlueXP 콘솔에 액세스합니다.

* 액세스 권한은 어떻게 처리됩니까? * 계정 관리자만 서비스를 시작하고 워크로드를 검색할 수 있습니다(리소스 사용을 커밋하는 작업이 포함되므로). 이후 상호 작용은 모든 역할에 의해 수행될 수 있습니다.

* 어떤 장치 해상도가 가장 좋습니까? * BlueXP 랜섬웨어 방어에 권장되는 장치 해상도는 1920x1080 이상입니다.

* 어떤 브라우저를 사용해야 합니까? * 모든 최신 브라우저가 작동합니다.



== 다른 서비스와의 상호 작용

* BlueXP 랜섬웨어 방어는 NetApp ONTAP의 보호 설정을 인식합니까? *
예, BlueXP 랜섬웨어 보호는 ONTAP에서 설정된 스냅샷 일정을 검색합니다.

* BlueXP 랜섬웨어 보호를 사용하여 정책을 설정한 경우 향후 이 서비스에서만 변경해야 합니까? *
BlueXP 랜섬웨어 방어 서비스에서 정책을 변경하는 것이 좋습니다.

* BlueXP  랜섬웨어 방어는 BlueXP  백업 및 복구 및 SnapCenter와 어떻게 상호 작용합니까? *

BlueXP  랜섬웨어 방어는 다음 제품 및 서비스를 사용합니다.

* 파일 공유 워크로드에 대한 스냅샷 및 백업 정책을 검색하고 설정하는 BlueXP  백업 및 복구
* SnapCenter 또는 SnapCenter for VMware: 애플리케이션 및 VM 워크로드에 대한 스냅샷 및 백업 정책을 검색하고 설정합니다.


또한 BlueXP  랜섬웨어 방어 기능은 BlueXP  백업 및 복구와 SnapCenter/SnapCenter for VMware를 사용하여 파일 및 워크로드 정합성이 보장되는 복구를 수행합니다.



== 워크로드

* 워크로드를 구성하는 요소는 무엇입니까? * 워크로드는 애플리케이션, VM 또는 파일 공유입니다. 워크로드에는 단일 애플리케이션 인스턴스에서 사용하는 모든 볼륨이 포함됩니다. 예를 들어, ora3.host.com 에 구축된 Oracle DB 인스턴스는 해당 데이터와 로그에 대해 각각 vol1과 vol2를 가질 수 있습니다. 이러한 볼륨은 모두 Oracle DB 인스턴스의 특정 인스턴스에 대한 워크로드를 구성합니다.

* BlueXP 랜섬웨어 방어는 워크로드 데이터의 우선순위를 어떻게 정합니까? *
데이터 우선 순위는 생성된 스냅샷 복사본과 예약된 백업에 의해 결정됩니다.

워크로드 우선순위(중요, 표준, 중요)는 워크로드와 관련된 각 볼륨에 이미 적용된 스냅샷 주파수에 따라 결정됩니다.

link:rp-use-protect.html["워크로드 우선 순위 또는 중요도에 대해 알아보십시오"].

* BlueXP  랜섬웨어 방어는 어떤 워크로드를 지원합니까? *

BlueXP  랜섬웨어 방어 기능은 Oracle, MySQL, 파일 공유, VM, VM 데이터 저장소와 같은 워크로드를 식별할 수 있습니다.

또한 고객이 SnapCenter 또는 SnapCenter for VMware를 사용 중인 경우 해당 제품에서 지원되는 모든 워크로드가 BlueXP  랜섬웨어 방어에서 확인되며 BlueXP  랜섬웨어 방어를 통해 워크로드를 일관적으로 보호하고 복구할 수 있습니다.

* 데이터를 워크로드와 연결하려면 어떻게 해야 합니까? *

BlueXP  랜섬웨어 방어는 다음과 같은 방식으로 데이터를 워크로드와 연결합니다.

* BlueXP  랜섬웨어 방어는 볼륨 및 파일 확장명을 검색하고 이를 적절한 워크로드에 연결합니다.
* 또한 VMware용 SnapCenter 또는 SnapCenter가 있고 BlueXP  백업 및 복구 환경에서 워크로드를 구성한 경우, BlueXP  랜섬웨어 방어는 SnapCenter 및 SnapCenter for VMware에서 관리하는 워크로드와 관련 볼륨을 검색합니다.


* "보호된" 워크로드란 무엇입니까? * BlueXP  랜섬웨어 차단에서 1차 감지 정책을 사용하도록 설정한 워크로드는 "보호됨" 상태를 표시합니다. 현재는 ARP가 워크로드와 관련된 모든 볼륨에 활성화되어 있다는 것을 의미합니다.

* "위험" 워크로드란 무엇입니까? * 워크로드에 기본 감지 정책이 활성화되어 있지 않으면 백업 및 스냅샷 정책을 활성화한 경우에도 "위험에 처해 있습니다."

* 새 볼륨이 추가되었지만 아직 나타나지 않음 * 환경에 새 볼륨을 추가한 경우 검색을 다시 시작하고 새 볼륨을 보호하기 위해 보호 정책을 적용합니다.

*대시보드에는 내 작업량이 모두 표시되지 않습니다. 무엇이 잘못되었을 수 있습니까? * 현재 NFS 및 CIFS 볼륨만 지원됩니다. iSCSI 볼륨 및 기타 지원되지 않는 구성은 필터링되어 대시보드에 표시되지 않습니다.



== 보호 정책

* BlueXP 랜섬웨어 정책은 다른 종류의 워크로드 정책과 공존합니까? *
현재 BlueXP 백업 및 복구(Cloud Backup)는 볼륨당 하나의 백업 정책을 지원합니다. BlueXP 백업 및 복구와 BlueXP 랜섬웨어 방어는 백업 정책을 공유합니다.

Snapshot 복사본은 제한되지 않으며 각 서비스와 별도로 추가할 수 있습니다.

* 랜섬웨어 방지 전략에 필요한 정책은 무엇입니까? *

랜섬웨어 보호 전략에는 다음 정책이 필요합니다.

* 랜섬웨어 감지 정책
* 스냅샷 정책


BlueXP  랜섬웨어 방지 전략에서 백업 정책이 필요하지 않습니다.

* BlueXP 랜섬웨어 방어는 NetApp ONTAP의 보호 설정을 인식합니까? *

예. BlueXP  랜섬웨어 방어는 ONTAP에 설정된 스냅샷 일정과 검색된 워크로드의 모든 볼륨에서 ARP 및 FPolicy가 활성화되는지 여부를 검색합니다. 대시보드의 처음에 표시되는 정보는 다른 NetApp 솔루션 및 제품에서 집계됩니다.

* BlueXP  랜섬웨어 방어는 BlueXP  백업 및 복구와 SnapCenter에 이미 적용된 정책을 인식하고 있습니까? *

예, BlueXP  백업 및 복구 또는 SnapCenter에서 관리되는 워크로드가 있는 경우 해당 제품에서 관리되는 정책이 BlueXP  랜섬웨어 방어에 적용됩니다.

* BlueXP  백업 및 복구 및/또는 SnapCenter에서 이월된 정책을 수정할 수 있습니까? *

아니요, BlueXP  랜섬웨어 보호 내에서 BlueXP  백업 및 복구 또는 SnapCenter로 관리되는 정책을 수정할 수 없습니다. BlueXP  백업 및 복구 또는 SnapCenter에서 이러한 정책에 대한 변경 사항을 관리합니다.

* ONTAP에서 정책이 있는 경우(ARP, FPolicy 및 스냅샷과 같은 시스템 관리자에서 이미 활성화됨) BlueXP  랜섬웨어 보호에서 변경된 정책입니까? *

아니요 BlueXP  랜섬웨어 방어 기능은 ONTAP의 기존 감지 정책(ARP, FPolicy 설정)을 수정하지 않습니다.

* BlueXP  랜섬웨어 방지에 등록한 후 BlueXP  백업 및 복구 또는 SnapCenter에 새로운 정책을 추가하면 어떻게 됩니까? *

BlueXP  랜섬웨어 방어는 BlueXP  백업 및 복구 또는 SnapCenter에서 생성된 모든 새로운 정책을 인식합니다.

* ONTAP에서 정책을 변경할 수 있습니까? *

예, BlueXP  랜섬웨어 방어에서 ONTAP의 정책을 변경할 수 있습니다. BlueXP  랜섬웨어 보호에서 새로운 정책을 생성하여 워크로드에 적용할 수도 있습니다. 이 동작은 기존 ONTAP 정책을 BlueXP  랜섬웨어 보호에서 생성된 정책으로 대체합니다.

* 정책을 비활성화할 수 있습니까? *

System Manager UI, API 또는 CLI를 사용하여 감지 정책에서 ARP를 사용하지 않도록 설정할 수 있습니다.

FPolicy 및 백업 정책은 포함되지 않은 다른 정책을 적용하여 사용하지 않도록 설정할 수 있습니다.
