= Digital Advisor의 보안 위험 평가
:allow-uri-read: 




=== Digital Advisor의 보안 위험 평가

BlueXP  랜섬웨어 방어는 이제 NetApp Digital Advisor에서 클러스터와 관련된 높은 중요 보안 위험에 대한 정보를 수집합니다. 위험이 발견되면 BlueXP  랜섬웨어 방어는 대시보드의 * 권장 작업 * 창에서 "클러스터 <name>에서 알려진 보안 취약점을 해결합니다."라는 권장 사항을 제공합니다. 대시보드의 권장 사항에서 * 검토 및 수정 * 을 클릭하면 Digital Advisor 및 CVE(Common Vulnerability & Exposure) 문서를 검토하여 보안 위험을 해결할 수 있습니다. 여러 보안 위험이 있는 경우 Digital Advisor의 정보를 검토하십시오.

을 https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor 설명서"^]참조하십시오.



=== Google Cloud Platform으로 백업하십시오

이 릴리즈에서는 백업 대상을 Google Cloud Platform 버킷으로 설정할 수 있습니다. 이전에는 백업 대상을 NetApp StorageGRID, Amazon Web Services, Microsoft Azure에만 추가할 수 있었습니다.

https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["BlueXP  랜섬웨어 차단 설정 구성 에 대해 자세히 알아보십시오"]..



=== Google Cloud Platform 지원

이 서비스는 현재 스토리지 보호를 위해 Cloud Volumes ONTAP for Google Cloud Platform을 지원합니다. 이전에는 이 서비스는 Amazon Web Services 및 Microsoft Azure와 사내 NAS를 위한 Cloud Volumes ONTAP만 지원했습니다.

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["BlueXP  랜섬웨어 차단 및 지원되는 데이터 소스, 백업 대상 및 작업 환경에 대해 알아보십시오"]..



=== 역할 기반 액세스 제어

이제 RBAC(역할 기반 액세스 제어)를 사용하여 특정 활동에 대한 액세스를 제한할 수 있습니다. BlueXP  랜섬웨어 방어는 BlueXP 의 두 가지 역할, 즉 BlueXP  계정 관리자 와 계정 관리자(뷰어)를 사용합니다.

각 역할이 수행할 수 있는 작업에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["역할 기반 액세스 제어 Privileges"].
