= SAN 워크로드 지원
:allow-uri-read: 




=== SAN 워크로드 지원

이 릴리스에는 BlueXP ransomware protection 의 SAN 워크로드 지원이 포함되어 있습니다. 이제 NFS 및 CIFS 워크로드 외에도 SAN 워크로드를 보호할 수 있습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["BlueXP 랜섬웨어 방어의 사전 요구사항"]참조하십시오.



=== 향상된 작업 부하 보호

이 릴리스에는 데이터 보호 여부와 관계없이 워크로드를 보호하기 위한 향상된 워크플로가 포함되어 있습니다. SnapCenter 또는 BlueXP backup and recovery 와 같은 다른 NetApp 데이터 보호 도구를 사용하여 스냅샷이나 백업을 생성하는 경우, BlueXP ransomware protection 해당 도구를 감지하고 해당 정책을 유지할 수 있도록 지원합니다. 이번 릴리스에서는 해당 정책을 BlueXP ransomware protection 정책으로 대체하거나 기존 정책을 계속 사용할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["워크로드 보호"]참조하십시오.



=== 이메일 알림

BlueXP ransomware protection 잠재적 공격을 감지하면 BlueXP 알림에 알림이 표시되고, 설정하신 이메일 주소로 이메일이 전송됩니다. 또한, 서비스는 즉시 스냅샷을 생성합니다.

이 시점에서 심각도와 영향을 받는 리소스가 나열된 이메일을 확인하고 BlueXP ransomware protection *알림* 탭에서 잠재적 위험을 살펴봐야 합니다.

BlueXP ransomware protection 에서 SIEM(보안 및 이벤트 관리)을 구성한 경우 해당 서비스는 SIEM 시스템으로 경고 세부 정보를 전송합니다.

자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["감지된 랜섬웨어 알림 처리"]참조하십시오.
